export enum ItemTypeEnum {
  Amulets = 1,
  BodyArmors = 2,
  Boots = 3,
  Belts = 4,
  Circlets = 5,
  Gloves = 6,
  Helms = 7,
  Shields = 8,
  Rings = 9,
  Jewels = 10,
  Axes = 11,
  Crossbows = 12,
  Daggers = 13,
  Javelins = 14,
  Maces = 15,
  Polearms = 16,
  Scepter = 17,
  Spears = 18,
  Staves = 19,
  Swords = 20,
  ThrowingWeapons = 21,
  Wands = 22
}
